# Generated by Django 5.0.2 on 2024-03-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('buy_date', models.DateField()),
            ],
            options={
                'db_table': 'Buy',
                'ordering': ['buy_id'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Categories',
                'ordering': (['category_id'],),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'Location',
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('postal_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PostalCode',
                'ordering': ['postal_id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default='', max_digits=2)),
                ('image', models.ImageField(upload_to='productsImages/')),
                ('category_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.categories')),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Buy_details',
            fields=[
                ('buy_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.buy')),
                ('product_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.products')),
            ],
            options={
                'db_table': 'Buy_details',
                'ordering': ['buy_details_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.IntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('location_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.location')),
                ('postal_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.postalcode')),
            ],
            options={
                'db_table': 'User',
                'ordering': ['user_id'],
            },
        ),
        migrations.AddField(
            model_name='buy',
            name='user_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.user'),
        ),
    ]
