# Generated by Django 5.0.2 on 2024-03-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='buy',
            name='product_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.products'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
