# Generated by Django 5.0.2 on 2024-04-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_details',
            name='user_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commerce.user'),
        ),
    ]
