# Generated by Django 5.0.4 on 2024-04-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_categories_options_buy_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
