# Generated by Django 5.0.2 on 2024-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_buy_details_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_details',
            name='buy_code',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.buy'),
        ),
    ]
