# Generated by Django 5.0.4 on 2024-05-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_buy_details_buy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
