# Generated by Django 5.0.4 on 2024-05-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_products_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='python-commerce'),
        ),
    ]
