# Generated by Django 5.0.4 on 2024-05-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_products_sales_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to='python-commerce'),
        ),
    ]
