# Generated by Django 5.0.4 on 2024-05-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_products_losses_products_profits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='losses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='profits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
