# Generated by Django 5.0.4 on 2024-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_products_losses_alter_products_profits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sales',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
