# Generated by Django 5.0.4 on 2024-05-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_products_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='losses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='profits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
