# Generated by Django 5.0.4 on 2024-05-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_products_losses_alter_products_profits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='losses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='profits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
