# Generated by Django 5.0.2 on 2024-03-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('image', models.ImageField(null=True, upload_to='productsImages/')),
                ('category', models.ForeignKey(default='category', on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
    ]
